#define SV 2.0
#define SN ESP06
#define NODE_ID ESP06
#define TEMP_CHILD_ID 2
#define DS18_PIN 2
#define HCSR04_TRIG_PIN 1
#define HCSR04_ECHO_PIN 3
#define DIST_CHILD_ID 1
#define ENABLE_DS18
#define ENABLE_HCSR04
#define PINMODE2 INPUT
#define PINMODE0 INPUT
#define DISABLE_LOGGING
#define MAX_DISTANCE 220